export enum Role {

  ADMIN = 'ROLE_ADMIN',
  MANAGER = 'ROLE_MANAGER',
  USER = 'ROLE_USER',
  HR = 'ROLE_HR',
  SYSADMIN= 'ROLE_SYSADMIN',
  HEADADMIN ='ROLE_HEADADMIN',
  HEADFIN ='ROLE_HEADFIN',
  HEADPROCUREMENT ='ROLE_HEADPROCUREMENT',

  SECRETARYDEPUTYSECRETARY= 'ROLE_SECRETARY',
  HEADOFADMINISTRATION = 'ROLE_HEADOFADMINISTRATION',
  DEPUTYHEADOFADMINISTRATION= 'ROLE_DEPUTYHEADOFADMINISTRATION',
  PRINCIPALADMINISTRATIONOFFICER='ROLE_PRINCIPALADMINISTRATIONOFFICER',
  ADMINISTRATIONOFFICER = 'ROLE_ADMINISTRATION OFFICER',

  
}


